const restify = {
	BadRequestError: ErrorHandler,
	UnauthorizedError: ErrorHandler,
	PaymentRequiredError: ErrorHandler,
	ForbiddenError: ErrorHandler,
	NotFoundError: ErrorHandler,
	MethodNotAllowedError: ErrorHandler,
	NotAcceptableError: ErrorHandler,
	ProxyAuthenticationRequiredError: ErrorHandler,
	RequestTimeoutError: ErrorHandler,
	ConflictError: ErrorHandler,
	GoneError: ErrorHandler,
	LengthRequiredError: ErrorHandler,
	PreconditionFailedError: ErrorHandler,
	RequestEntityTooLargeError: ErrorHandler,
	RequesturiTooLargeError: ErrorHandler,
	UnsupportedMediaTypeError: ErrorHandler,
	RangeNotSatisfiableError: ErrorHandler,
	RequestedRangeNotSatisfiableError: ErrorHandler,
	ExpectationFailedError: ErrorHandler,
	ImATeapotError: ErrorHandler,
	UnprocessableEntityError: ErrorHandler,
	LockedError: ErrorHandler,
	FailedDependencyError: ErrorHandler,
	UnorderedCollectionError: ErrorHandler,
	UpgradeRequiredError: ErrorHandler,
	PreconditionRequiredError: ErrorHandler,
	TooManyRequestsError: ErrorHandler,
	RequestHeaderFieldsTooLargeError: ErrorHandler,
	InternalServerError: ErrorHandler,
	NotImplementedError: ErrorHandler,
	BadGatewayError: ErrorHandler,
	ServiceUnavailableError: ErrorHandler,
	GatewayTimeoutError: ErrorHandler,
	HttpVersionNotSupportedError: ErrorHandler,
	VariantAlsoNegotiatesError: ErrorHandler,
	InsufficientStorageError: ErrorHandler,
	BandwidthLimitExceededError: ErrorHandler,
	NotExtendedError: ErrorHandler,
	NetworkAuthenticationRequiredError: ErrorHandler,
};

function ErrorHandler(message) {}

module.exports = restify;
